### PR TITLE
Upgrade to Crystal 0.25.0 JSON::Any API

### PR DESCRIPTION
**Pull request by bcardiff**
This PR update the code to the future crystal 0.25 version regarding JSON::Any API.

Ref: https://github.com/crystal-lang/crystal/pull/5183

### CODE REVIEW

**Comment by docelic** [comment]
Hey @bcardiff awesome, thanks! What are your instructions for merging this? I see it does not work on 0.24.2 and 0.25 is not listed yet on https://github.com/crystal-lang/crystal/releases.

Do you suggest that this gets merged after 0.25 is released, and that we effectively start requiring 0.25 as minimum version after that?

**Comment by bcardiff** [comment]
Hi @docelic, it's up to you if you want to try to keep compatibility with 0.24.2, but that will requiere some ifdef/responds_to checks in the code.

My suggestion would be to wait for merging until 0.25 is ready (last days where checking that the ecosystem is mostly ready for it without many issues, from that check this PR emerged :-) ). After 0.25 is release I would suggest a new release changing the minor version. Later and only if needed, a patch version can be released with backported features and  0.24.2 support.

**Comment by docelic** [comment]
We'll do so, thanks!

**Comment by faustinoaq** [comment]
Fixes #33 Thank you @bcardiff !

**Pull request merged**
